**Indexing and Slicing an Array using NumPy**

Importing NumPy as np for the ease of writing code

In [48]:
import numpy as np

Defining an example array

In [49]:
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


You can index or slice numpy arrays to get specific values or elements out of the given array

Getting an individual element

In [60]:
print(a[0, 1])
print(a[1, 2])
print(a[2, 0])

20
60
70


Getting a row

In [51]:
print(a[1])
print(a[2])

[40 50 60]
[70 80 90]


Getting multiple rows

In [52]:
print(a[0:2])
#or
print(a[0:-1])
#both of the above give us the same output

print(a[1:])
print(a[:2])

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [40 50 60]]
[[40 50 60]
 [70 80 90]]
[[10 20 30]
 [40 50 60]]


We can also sort out values in an array that are equal to, less than or more than a certain value

In [53]:
print(a[a<50])
print(a[a>50])
print(a[a==50])

[10 20 30 40]
[60 70 80 90]
[50]


We can sort out elements that are divisible by a certain value

In [71]:
print(a[a%6==0])

[20 40 60 80]


We can also sort out elements that satisfy multiple values with the use of & (and operator) and | (or operator)

In [73]:
print(a[(a%4==0) & (a>40)])

[60 80]


We can also check whether the elements of an array fulfill a certain condition

In [75]:
print(a<=50)
print(a%6==0)
print(a==70)

[[ True  True  True]
 [ True  True False]
 [False False False]]
[[False False  True]
 [False False  True]
 [False False  True]]
[[False False False]
 [False False False]
 [ True False False]]
