**Adding, Removing and Sorting Elements of an Array** 

Importing NumPy as np

In [88]:
import numpy as np

Sorting the elements of an array in ascending order

In [89]:
a = np.array([1, 3, 5, 9, 4, 7, 6, 2, 8])
print(a)

[1 3 5 9 4 7 6 2 8]


In [90]:
a = np.sort(a)
print(a)

[1 2 3 4 5 6 7 8 9]


In addition to np.sort you can use:

np.argsort, which is an indirect sort along a specified axis \
np.lexsort, which is an indirect stable sort on multiple keys \
np.searchsorted, which will find elements in a sorted array, and \
np.partition, which is a partial sort.

Read more about sorting an array [here](ttps://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort)

You can also concatenate (join or combine) arrays

In [91]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [92]:
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6 7 8]


Or,

In [93]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]]


In [94]:
z = np.concatenate((x, y), axis=0)
print(z)

[[1 2]
 [3 4]
 [5 6]]


**Reshaping and Array**

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [95]:
a = np.arange(100, 200, 10)
print(a)

[100 110 120 130 140 150 160 170 180 190]


In [97]:
a = a.reshape(5, 2)
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
