**Array Creation with NumPy**

Importing numpy as np

In [96]:
import numpy as np

Creating a basic array

In [97]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Creating an array where every elements is a zero

In [98]:
a = np.zeros(3)
b = np.zeros([2, 3])
print(a)
print(b)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


Creating an array where all the elements are ones

In [99]:
a = np.ones(2)
b = np.ones([3, 2])
print(a)
print(b)

[1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


The np.empty function creates and empty array whose initial content is random and depends on the state of the memory 

In [100]:
a = np.empty([4, 3])
print(a)

[[6.79038654e-313 6.79038653e-313 2.37663529e-312]
 [2.14321575e-312 2.37663529e-312 2.56761491e-312]
 [1.93101617e-312 9.33678148e-313 1.14587773e-312]
 [8.70018275e-313 2.05833592e-312 8.34402697e-309]]


Creating an array with a range of elements

In [101]:
a = np.arange(4)
print(a)

[0 1 2 3]


An array that contains a range of elements with evenly spaced intervals can also be created with this function

In [102]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


Creating a specific number of equaly spaced elements between two given values

In [103]:
a = np.linspace(10, 100, 5)
print(a)

[ 10.   32.5  55.   77.5 100. ]


You can also specify the data type of the elements of an array while creating it

In [104]:
a = np.arange(10, 100, 10, dtype=np.int8)
print(a)

[10 20 30 40 50 60 70 80 90]
