**Basic Array Operations with NumPy**

Importing NumPy as np for the ease of writing code

In [101]:
import numpy as np

Defining A as an example array

In [102]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Finding the number of dimensions (number of axes) of an array

In [103]:
a.ndim

2

Finding the dimensions (shape) of an array

In [104]:
a.shape

(3, 3)

Finding the total number of elements in an array

In [105]:
a.size

9

Finding the data type of the elements in an array

In [106]:
a.dtype

dtype('int32')

Finding the size (in bytes) of each element in an array

In [107]:
a.itemsize

4

Finding the buffer containing the elements of an array (not that important)

In [108]:
a.data