**Array Creation with NumPy**

Importing numpy as np for the ease of writing code

In [85]:
import numpy as np

Creating a basic array

In [86]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


Creating an array where every elements is a zero

In [87]:
a = np.zeros(3)
b = np.zeros([2, 3])
print(a)
print(b)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


Creating an array where all the elements are ones

In [88]:
a = np.ones(2)
b = np.ones([3, 2])
print(a)
print(b)

[1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


The np.empty function creates an empty array whose initial content is random and depends on the state of the memory 

In [89]:
a = np.empty([4, 3])
print(a)

[[4.45057637e-308 1.78021527e-306 8.45549797e-307]
 [1.37962049e-306 1.11260619e-306 1.78010255e-306]
 [9.79054228e-307 4.45057637e-308 8.45596650e-307]
 [9.34602321e-307 4.94065646e-322 8.34402697e-309]]


Creating an array with a range of elements

In [90]:
a = np.arange(4)
print(a)

[0 1 2 3]


An array that contains a range of elements with evenly spaced intervals can also be created with this function

In [91]:
a = np.arange(1, 10, 2)
print(a)

[1 3 5 7 9]


Creating a specific number of equaly spaced elements between two given values

In [92]:
a = np.linspace(10, 100, 5)
print(a)

[ 10.   32.5  55.   77.5 100. ]


You can also specify the data type of the elements of an array while creating it

In [93]:
a = np.arange(10, 100, 10, dtype=np.int8)
print(a)

[10 20 30 40 50 60 70 80 90]


**Creating Arrays from existing Arrays**

Slicing an array

In [94]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [95]:
b = a[3:7]
print(b)

[3 4 5 6]


Stacking arrays

In [96]:
a = np.arange(1, 5, 1).reshape(2, 2)
b = np.arange(5, 9, 1).reshape(2, 2)
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [97]:
# stacking arrays vertically

v = np.vstack((a, b))
print(v)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [98]:
# stacking arrays horizontally

h = np.hstack((a, b))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


We can also split any given array into multiple arrays

In [99]:
a = np.linspace(0, 190, 20).reshape(4, 5)
print(a)

[[  0.  10.  20.  30.  40.]
 [ 50.  60.  70.  80.  90.]
 [100. 110. 120. 130. 140.]
 [150. 160. 170. 180. 190.]]


In [100]:
# splitting your array into 5 equally shaped arrays vertically and horizontally

print(np.vsplit(a, 4))
print(np.hsplit(a, 5))

[array([[ 0., 10., 20., 30., 40.]]), array([[50., 60., 70., 80., 90.]]), array([[100., 110., 120., 130., 140.]]), array([[150., 160., 170., 180., 190.]])]
[array([[  0.],
       [ 50.],
       [100.],
       [150.]]), array([[ 10.],
       [ 60.],
       [110.],
       [160.]]), array([[ 20.],
       [ 70.],
       [120.],
       [170.]]), array([[ 30.],
       [ 80.],
       [130.],
       [180.]]), array([[ 40.],
       [ 90.],
       [140.],
       [190.]])]


We can also split certain columns or rows from an array

In [101]:
# splitting third and fifth row from an array
print(np.vsplit(a, (2, 4)))

[array([[ 0., 10., 20., 30., 40.],
       [50., 60., 70., 80., 90.]]), array([[100., 110., 120., 130., 140.],
       [150., 160., 170., 180., 190.]]), array([], shape=(0, 5), dtype=float64)]


In [102]:
# splitting first and second column from an array
print(np.hsplit(a, (0, 1)))

[array([], shape=(4, 0), dtype=float64), array([[  0.],
       [ 50.],
       [100.],
       [150.]]), array([[ 10.,  20.,  30.,  40.],
       [ 60.,  70.,  80.,  90.],
       [110., 120., 130., 140.],
       [160., 170., 180., 190.]])]
